id: AD79BA449
title: A Prayer to the Precious Teacher of Incomparable Kindness, Jamyang Lungtok
  Gyaltsen
type: translation
pechas:
- I94FC9F4F
- I6C8543B7
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:27:50.362340
  last_modified_at: 2023-01-04 11:27:50.362347
  collections:
  - Akhyuk Rinpoche Lungtok Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  I94FC9F4F/F319: E205
  I6C8543B7/F0CE: E205
